FROM ubuntu:14.04
#update and install pre-requisites
RUN apt-get update
RUN apt-get install sudo -y
RUN sudo apt-get install curl -y
RUN sudo apt-get install apt-transport-https -y
RUN sudo apt-get update -y
RUN sudo apt-get install unzip -y

#Setup older PowerShell for compatibility with PowerCLI_Core
RUN curl -SLO https://github.com/PowerShell/PowerShell/releases/download/v6.0.0-alpha.18/powershell_6.0.0-alpha.18-1ubuntu1.14.04.1_amd64.deb
RUN apt-get install libunwind8 libicu52 libcurl3 -y
RUN dpkg -i powershell_6.0.0-alpha.18-1ubuntu1.14.04.1_amd64.deb
RUN apt-get install -f

#install SolidFire 1.4 bits
RUN sudo su
RUN mkdir -p /usr/local/share/powershell/Modules/SolidFire
RUN cd /usr/local/share/powershell/Modules/SolidFire && curl --remote-name-all https://raw.githubusercontent.com/solidfire/sdk-dotnet/master/package/SolidFire.SDK.dll https://raw.githubusercontent.com/solidfire/PowerShell/1.4/packages/Newtonsoft.Json.dll https://raw.githubusercontent.com/solidfire/PowerShell/1.4/packages/SolidFire.dll https://raw.githubusercontent.com/solidfire/PowerShell/1.4/packages/SolidFire.psd1 https://raw.githubusercontent.com/solidfire/PowerShell/1.4/packages/Initialize-SFEnvironment.ps1 https://raw.githubusercontent.com/solidfire/PowerShell/1.4/packages/SolidFire.dll-help.xml >/dev/null && cd -
RUN  echo ". /usr/local/share/powershell/Modules/SolidFire/Initialize-SFEnvironment.ps1" > /opt/microsoft/powershell/6.0.0-alpha.18/profile.ps1

#install PowerCLI Pre-requisites
RUN echo "Get-Module -ListAvailable PowerCLI* | Import-Module" >> /opt/microsoft/powershell/6.0.0-alpha.18/profile.ps1
RUN echo "Set-PowerCLIConfiguration  -InvalidCertificateAction Ignore" >> /opt/microsoft/powershell/6.0.0-alpha.18/profile.ps1

#NOTE - THIS IMAGE IS ONLY FOR PRE-REQUISITES. YOU NEED TO FOLLOW THE INSTRUCTIONS TO COMPLETE THE BUILD WITH POWERCLI_CORE
